#!/bin/sh

# menu-ext-adv: terminal menu with configurable action keys, backed by menu.lib.sh.
#
# Usage:
#   menu-ext-adv [-H header] [-F footer] [-B bottom-footer] -K key [-K key ...] -- item ...
#
# Each item is either:
#   text
#   value@:=text
#
# A configured key returns:
#   key@:=value
#
# Escape always cancels. Navigation keys are reserved and cannot be configured.
# The terminal UI is handled by menu.lib.sh through term.lib.sh; stdout is
# reserved for the result.

. menu.lib.sh

header=
footer=
bottom_footer=
custom_key_count=0
newline='
'

usage()
{
  printf '%s\n' \
    'usage: menu-ext-adv [-H header] [-F footer] [-B bottom-footer] -K key [-K key ...] -- item ...' \
    '' \
    'options:' \
    '  -H text        header at the top of the screen' \
    '  -F text        footer immediately after the last visible item' \
    '  -B text        footer anchored at the bottom of the screen' \
    '  -K key         configured action key; may be repeated' \
    '' \
    'item forms:' \
    '  text           display and select text' \
    '  value@:=text   display text and select value' \
    '' \
    'custom key forms:' \
    '  x              one printable ASCII character' \
    '  space          Space' \
    '  tab            Tab' \
    '  enter          Enter/Return' \
    '  backspace      Backspace' \
    '  delete         Delete' \
    '  insert         Insert' \
    '  arrow_left     Left arrow' \
    '  arrow_right    Right arrow' \
    '  f1 ... f20     function keys' \
    '' \
    'reserved keys:' \
    '  esc            cancel' \
    '  arrow_up       move up' \
    '  arrow_down     move down' \
    '  pageup         move one page up' \
    '  pagedown       move one page down' \
    '  home           move to first item' \
    '  end            move to last item'
}

fail()
{
  printf 'menu-ext-adv: %s\n' "$1" >&2
  exit 2
}

split_item()
{
  case "$1" in
    *@:=*)
      item_value="${1%%@:=*}"
      item_text="${1#*@:=}"
      ;;
    *)
      item_value="$1"
      item_text="$1"
      ;;
  esac
}

legacy_key_to_menu()
{
  case "$1" in
    esc|arrow_up|arrow_down|pageup|pagedown|home|end)
      fail "key is reserved: $1"
      ;;
    space)
      mapped_key=' '
      ;;
    arrow_left)
      mapped_key=left
      ;;
    arrow_right)
      mapped_key=right
      ;;
    tab|enter|backspace|delete|insert|f1|f2|f3|f4|f5|f6|f7|f8|f9|f10|f11|f12|f13|f14|f15|f16|f17|f18|f19|f20)
      mapped_key="$1"
      ;;
    *)
      candidate_size="$(LC_ALL=C printf '%s' "$1" | wc -c | tr -d '[:space:]')" ||
        fail "cannot validate custom key: $1"

      if [ "$candidate_size" != "1" ]
      then
        fail "invalid custom key: $1"
      fi

      candidate_byte="$(LC_ALL=C printf '%s' "$1" | od -A n -t u1 | tr -d '[:space:]')" ||
        fail "cannot validate custom key: $1"

      case "$candidate_byte" in
        ''|*[!0-9]*) fail "invalid custom key: $1" ;;
      esac

      if [ "$candidate_byte" -eq 32 ]
      then
        fail 'use key alias space instead of a literal space'
      fi

      if [ "$candidate_byte" -lt 33 ] || [ "$candidate_byte" -gt 126 ]
      then
        fail "invalid custom key: $1"
      fi

      mapped_key="$1"
      ;;
  esac
}

add_custom_key()
{
  legacy_key_to_menu "$1"

  if map menu_ext_adv_key_aliases get "$mapped_key" menu_ext_adv_existing_alias >/dev/null 2>&1
  then
    fail "duplicate custom key: $1"
  fi

  map menu_ext_adv_key_aliases put "$mapped_key" "$1" ||
    fail "cannot store custom key: $1"

  if [ "$mapped_key" != "enter" ]
  then
    menu_key_add "$mapped_key" || fail "$menu_error"
  fi

  custom_key_count="$((custom_key_count + 1))"
}

menu_ext_adv_provider()
{
  case "$1" in
    event)
      [ "$#" -eq 5 ] || return 2

      if map menu_ext_adv_key_aliases get "$2" menu_ext_adv_result_alias >/dev/null 2>&1
      then
        menu_provider_action=return
      else
        menu_provider_action=ignore
      fi

      return 0
      ;;
  esac

  menu_array_provider "$@"
}

menu_reset || fail 'cannot initialize menu engine'
map menu_ext_adv_key_aliases || fail 'cannot initialize custom-key map'

while getopts ':H:F:B:K:h' option
do
  case "$option" in
    H)
      header="$OPTARG"
      ;;
    F)
      footer="$OPTARG"
      ;;
    B)
      bottom_footer="$OPTARG"
      ;;
    K)
      add_custom_key "$OPTARG"
      ;;
    h)
      usage
      exit 0
      ;;
    :)
      fail "option -$OPTARG requires an argument"
      ;;
    \?)
      fail "unknown option: -$OPTARG"
      ;;
  esac
done

if [ "$custom_key_count" -eq 0 ]
then
  fail 'at least one -K custom key is required'
fi

delimiter_index="$((OPTIND - 1))"
index=1
delimiter_seen=0

for argument
do
  if [ "$index" -eq "$delimiter_index" ]
  then
    if [ "$argument" = "--" ]
    then
      delimiter_seen=1
    fi
    break
  fi

  index="$((index + 1))"
done

shift "$delimiter_index"

if [ "$delimiter_seen" -ne 1 ]
then
  fail 'missing -- before menu items'
fi

if [ "$#" -eq 0 ]
then
  fail 'at least one menu item is required'
fi

array menu_ext_adv_values || fail 'cannot initialize menu values'
array menu_ext_adv_labels || fail 'cannot initialize menu labels'

for item
do
  split_item "$item"

  case "$item_text" in
    *"$newline"*) fail 'menu item text must be a single line' ;;
  esac

  array menu_ext_adv_values add "$item_value" || fail 'cannot store menu value'
  array menu_ext_adv_labels add "$item_text" || fail 'cannot store menu label'
done

menu_header="$header"
menu_footer="$footer"
menu_bottom_footer="$bottom_footer"
menu_array_values=menu_ext_adv_values
menu_array_labels=menu_ext_adv_labels

menu_run_provider menu_ext_adv_provider
status="$?"

case "$status" in
  0)
    if ! map menu_ext_adv_key_aliases get "$menu_result_key" result_key >/dev/null 2>&1
    then
      fail 'menu engine returned an unconfigured key'
    fi

    printf '%s@:=%s\n' "$result_key" "$menu_result_value"
    exit 0
    ;;
  1)
    exit 1
    ;;
  2)
    if [ -n "$menu_error" ]
    then
      fail "$menu_error"
    fi
    fail 'menu engine failed'
    ;;
  *)
    exit "$status"
    ;;
esac
