#!/bin/sh

# menu-ext: terminal-menu frontend backed by menu.lib.sh.
#
# Usage:
#   menu-ext [-H header] [-F footer] [-B bottom-footer] -- item ...
#
# Each item is either:
#   text
#   value@:=text
#
# The selected value is written to standard output. The terminal UI is handled
# by menu.lib.sh through term.lib.sh, so command substitution remains usable.

. menu.lib.sh

header=
footer=
bottom_footer=

usage()
{
  printf '%s\n' \
    'usage: menu-ext [-H header] [-F footer] [-B bottom-footer] -- item ...' \
    '' \
    'options:' \
    '  -H text        header at the top of the screen' \
    '  -F text        footer immediately after the last visible item' \
    '  -B text        footer anchored at the bottom of the screen' \
    '' \
    'item forms:' \
    '  text           display and return text' \
    '  value@:=text   display text and return value' \
    '' \
    'keys:' \
    '  Up/Down, PageUp/PageDown, Home/End  move' \
    '  Enter                                select' \
    '  q, Esc                               cancel'
}

fail()
{
  printf 'menu-ext: %s\n' "$1" >&2
  exit 2
}

split_item()
{
  case "$1" in
    *@:=*)
      item_value="${1%%@:=*}"
      item_text="${1#*@:=}"
      ;;
    *)
      item_value="$1"
      item_text="$1"
      ;;
  esac
}

menu_ext_provider()
{
  case "$1" in
    event)
      [ "$#" -eq 5 ] || return 2

      if [ "$2" = "q" ]
      then
        menu_provider_action=cancel
        return 0
      fi
      ;;
  esac

  menu_array_provider "$@"
}

while getopts ':H:F:B:h' option
do
  case "$option" in
    H)
      header="$OPTARG"
      ;;
    F)
      footer="$OPTARG"
      ;;
    B)
      bottom_footer="$OPTARG"
      ;;
    h)
      usage
      exit 0
      ;;
    :)
      fail "option -$OPTARG requires an argument"
      ;;
    \?)
      fail "unknown option: -$OPTARG"
      ;;
  esac
done

delimiter_index="$((OPTIND - 1))"
index=1
delimiter_seen=0

for argument
do
  if [ "$index" -eq "$delimiter_index" ]
  then
    if [ "$argument" = "--" ]
    then
      delimiter_seen=1
    fi
    break
  fi

  index="$((index + 1))"
done

shift "$delimiter_index"

if [ "$delimiter_seen" -ne 1 ]
then
  fail 'missing -- before menu items'
fi

if [ "$#" -eq 0 ]
then
  fail 'at least one menu item is required'
fi

array menu_ext_values || fail 'cannot initialize menu values'
array menu_ext_labels || fail 'cannot initialize menu labels'

newline='
'
for item
do
  split_item "$item"

  case "$item_text" in
    *"$newline"*) fail 'menu item text must be a single line' ;;
  esac

  array menu_ext_values add "$item_value" || fail 'cannot store menu value'
  array menu_ext_labels add "$item_text" || fail 'cannot store menu label'
done

menu_reset || fail 'cannot initialize menu engine'
menu_header="$header"
menu_footer="$footer"
menu_bottom_footer="$bottom_footer"
menu_array_values=menu_ext_values
menu_array_labels=menu_ext_labels

menu_key_add q || fail "$menu_error"

menu_run_provider menu_ext_provider
status="$?"

case "$status" in
  0)
    printf '%s\n' "$menu_result_value"
    exit 0
    ;;
  1)
    exit 1
    ;;
  2)
    if [ -n "$menu_error" ]
    then
      fail "$menu_error"
    fi
    fail 'menu engine failed'
    ;;
  *)
    exit "$status"
    ;;
esac
